# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93834a3dce2a732d0aab09dce00785fa68c95c72c44334be0520ac3d891cab70112063009a826e0942ddeb640f888f62d829e742da010e681340973ea4711cb0

test:
  secret_key_base: 27ed534337df2aa65451a1b1c040957ffe2d2f56b79cae5e8b38e53dc8ea1580c4550daa8d50a3ccf671a1d008784dfade98ba9ce15102369091a95c2d1620a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
